################################################################################
# ServiceAccount for the EC2 VM workload
# The VM will use this SA identity within the Istio mesh (mTLS)
################################################################################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sender-vm
  namespace: default
  labels:
    app: sender-vm
