apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: default
  labels:
    app: receiver
spec:
  selector:
    app: receiver
  ports:
  - name: http
    port: 80
    targetPort: 5678
    protocol: TCP
  type: ClusterIP
