# ServiceAccount para la VM en el mesh de Istio
# La VM usa esta identidad para mTLS dentro del mesh
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sender-vm
  namespace: default
  labels:
    app: sender-vm
